- app/api/docs/$$.mjs
- app/elements/docs/outline.mjs
> Add edit doc link

- app/elements/doc/video.mjs
> Change Mux player link

- app/docs/md/learn/starter-project/head.md
Updates documentation for `<head>` template
> Head documentation update for accepting API data

- app/docs/md/learn/deployment/begin.md
> add disclaimer to deploy/begin doc

- app/docs/md/learn/deployment/begin.md
I initially was a bit confused when testing Enhance.dev about what this Begin tool is. Maybe a link to the project helps others to understand.
> Link to begin.com

- app/docs/md/learn/get-started/editor-setup.md
Small addition for the Neovim fans!
> Add editor setup info for Neovim

- app/docs/md/learn/starter-project/elements.md
- package-lock.json
- package.json
> When a project grows to include more elements than can comfortably fit in a single folder, they can be divided into sub-directories inside `app/elements/`. The folder name becomes part of the custom element tag name:
```
app/elements/blog/comment → <blog-comment></blog-comment>
app/elements/blog/comment-form → <blog-comment-form></blog-comment-form>
```
and dependency updates
> add description for app/elements/ sub-directories

- app/docs/md/learn/concepts/styling/utility-classes.md
depends on https://github.com/enhance-dev/arc-plugin-enhance/pull/48
> update for arc-plugin-styles 2.2

- app/docs/md/learn/concepts/state/attributes.md
> Named attributes

- app/docs/md/by-example/integrations/with-tailwind.md
Per the tutorial linked below, I had to add the tailwind src in order to get this to work.
https://blog.begin.com/posts/2022-09-22-using-tailwind-with-enhance
> docs(css): add tailwind src

- app/docs/md/learn/practices/env-vars.md
updated debug page render function signature, removed `async`, causes 500 error
> updated debug page render function signature

- app/elements/docs/layout.mjs
- app/elements/nav-bar.mjs
> Issue #54: Our multiple nav elements should have aria-labels

- app/head.mjs
> Issue #106: Add individual titles to the docs pages

- app/docs/md/learn/concepts/glossary.md
- app/docs/nav-data.mjs
- app/head.mjs
there's not a lot of structure here, but I didn't want to put everything in one alphabetical list.
looking for feedback about content, presentation, additions, deletions etc
> Glossary starter doc

- app/docs/md/by-example/examples/typescript-web-components.md
- app/docs/md/learn/starter-project/browser.md
- app/docs/md/learn/starter-project/structure.md
- app/docs/md/unsorted/browser-modules.md
- app/docs/nav-data.mjs
- scripts/dictionary.txt
This update documents the workflow the new arc-plugin-rollup plugin enables.
> Adds documentation for the "browser" pattern

- app/docs/nav-data.mjs
- app/elements/docs/outline.mjs
- app/pages/cta.html
Adds a link to verify our Mastodon account
> Add rel="me" links

- app/api/cta/$event.mjs
- app/api/cta/views.mjs
- package-lock.json
- package.json
> Server side analytics

- app/docs/md/learn/starter-project/public.md
> Updates link to browser-modules doc

- app/pages/index.html
> style: smooth scroll behaviour

- app/docs/md/learn/practices/testing/webdriverio.md
We have moved to Discord. Let's update the channel link.
> (docs): Update WebdriverIOs community channel

- app/docs/md/by-example/examples/browser-testing.md
- app/docs/md/index.md
- app/docs/md/learn/concepts/routing/api-routes.md
- app/docs/md/learn/deployment/architect.md
- app/docs/md/learn/deployment/begin.md
- app/docs/md/learn/starter-project/public.md
> Use enhance/cli in docs

- app/docs/md/learn/showcase.md
Hello 👋 
Love the project and was thrilled to see the showcase page to highlight what's possible (and being built) with Enhance. Noticed that one of the projects had the incorrect link, so threw together this PR to correct it.
Thanks again!
> correct perfwork showcase link

- app/docs/md/enhance-styles/modular-scales.md
Just a small docs heading word change
> spaceScale rather than fontScale

- app/docs/md/conventions/head.md
- app/docs/md/routing/api-routes/index.md
> API examples

- package-lock.json
- package.json
- scripts/dictionary.txt
Updates products to say Begin Deploy instead of Begin CLI.
> Bump imprint

- app/docs/md/patterns/form-validation.md
Based off conversation: https://discord.com/channels/1012099764713705472/1012435743571988560/1208432130837970964 where I tried to use this and ran into generic Lambda errors
> Attempting to fix the example

- app/docs/md/index.md
> Emphasize .html custom elements in the Quick Start

- app/docs/md/patterns/event-listeners.md
- app/docs/nav-data.mjs
I noticed folks were trying to figure out how to do event listeners.
> Add event listener doc

- app/docs/md/conventions/components.md
Just a small typo I noticed while reading this.
> Correct typo for custom element registry object

- app/api/docs/$$.mjs
Fixes Issue #207 
If you ask for a doc that doesn't exist it sends you to the 404 page.
> Issue #207: Docs 404 is missing
